version: '3.2'

services:

 mariadb:
  image: mariadb
  restart: always
  networks:
   - backend1
   - backend2
  environment:
   - MYSQL_ROOT_PASSWORD=rootpassword
  ports:
   - 3306:3306
  volumes:
   - dbdata:/var/lib/mysql
   
 php1:
  build: './php1/'
  networks:
   - backend1
  volumes:
   - ./serveur1/html:/usr/local/apache2/htdocs
   
 php2:
  build: './php2/'
  networks:
   - backend2
  volumes:
   - ./serveur2/html:/usr/local/apache2/htdocs
   
 serveur1:
  build: './serveur1/'
  depends_on:
   - php1
   - mariadb
  networks:
   - frontend
   - backend1
  volumes:
   - ./serveur1/html:/usr/local/apache2/htdocs
   
 serveur2:
  build: './serveur2/'
  depends_on:
   - php2
   - mariadb
  networks:
   - frontend
   - backend2
  volumes:
   - ./serveur2/html:/usr/local/apache2/htdocs
   
 proxy:
  image: nginx:alpine
  networks:
   - frontend
  ports:
   - 80:80
  volumes:
   - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
 frontend:
 backend1:
 backend2:

volumes:
 dbdata:
